language: ruby

services:
  - postgresql

before_script:
  - psql -c 'create database ruby-getting-started_test;' -U postgres
  - cp config/database.yml.travis config/database.yml


test:
  adapter: postgresql
  database: ruby-getting-started_test

