language: ruby

services:
  - postgresql

before_script:
  #- cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

test:
  #adapter: postgresql
  #database: ruby-getting-started_test
  adapter: postgresql
  database: travis_ci_test
  
notifications:
  email: false


